# Generated by Django 4.1.2 on 2022-11-06 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_subject_department_alter_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(default='CSE', on_delete=django.db.models.deletion.CASCADE, to='account.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 9, 20, 2, 198363, tzinfo=datetime.timezone.utc)),
        ),
    ]
