# Generated by Django 4.1.2 on 2022-11-01 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 20, 3, 4, 731062, tzinfo=datetime.timezone.utc)),
        ),
    ]
