# Generated by Django 4.1.2 on 2022-11-02 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_student_pic_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='', upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(default='', upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 35, 43, 466496, tzinfo=datetime.timezone.utc)),
        ),
    ]
