# Generated by Django 4.1.2 on 2022-10-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_created_at_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USN',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='userID',
        ),
    ]
