# Generated by Django 4.1.2 on 2022-11-02 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_teacher_pic_alter_student_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 42, 31, 251427, tzinfo=datetime.timezone.utc)),
        ),
    ]
