# Generated by Django 4.1.2 on 2022-11-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_student_address_student_blood_group_student_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pic',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 13, 36, 29, 583992, tzinfo=datetime.timezone.utc)),
        ),
    ]
