# Generated by Django 4.1.2 on 2022-11-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_otp_remove_user_otp_created_at_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'classattendance')},
        ),
    ]
