# Generated by Django 4.1.2 on 2022-11-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_otp_created_at'),
        ('account', '0010_student_father_name_alter_user_otp_created_at'),
    ]

    operations = [
    ]
