# Generated by Django 4.1.2 on 2022-11-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20221102_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 14, 35, 15, 856168, tzinfo=datetime.timezone.utc)),
        ),
    ]
