# Generated by Django 4.1.2 on 2022-11-04 11:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20221104_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('lastedit', models.DateTimeField(auto_now=True)),
                ('showto', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-lastedit'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 41, 38, 748799, tzinfo=datetime.timezone.utc)),
        ),
    ]
