# Generated by Django 4.1.2 on 2022-11-03 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_student_mother_name_student_mother_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSectionSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('lastedit', models.DateTimeField(auto_now=True)),
                ('showto', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-lastedit'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 18, 56, 18, 31653, tzinfo=datetime.timezone.utc)),
        ),
    ]
