# Generated by Django 4.1.2 on 2022-11-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_student_mother_name_student_mother_phone_and_more'),
        ('account', '0013_updates_student_mother_name_student_mother_phone_and_more'),
    ]

    operations = [
    ]
