# Generated by Django 4.1.2 on 2022-11-04 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_department_student_mother_name_student_mother_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name_plural': 'klasses'},
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 14, 38, 0, 824678, tzinfo=datetime.timezone.utc)),
        ),
    ]
