# Generated by Django 4.1.2 on 2022-11-03 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merge_20221104_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 20, 0, 14, 533275, tzinfo=datetime.timezone.utc)),
        ),
    ]
