# Generated by Django 4.1.2 on 2022-11-04 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_updates_update_alter_klass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 14, 45, 26, 600944, tzinfo=datetime.timezone.utc)),
        ),
    ]
