# Generated by Django 4.1.2 on 2022-11-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_updates_student_mother_name_student_mother_phone_and_more'),
        ('account', '0014_updatesectionserializer_alter_user_otp_created_at'),
    ]

    operations = [
    ]
