# Generated by Django 4.1.2 on 2022-11-03 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_delete_updatesectionserializer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 19, 13, 57, 361387, tzinfo=datetime.timezone.utc)),
        ),
    ]
