# Generated by Django 4.1.2 on 2022-11-04 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_otp_created_at_subject_assignclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignclass',
            options={'verbose_name_plural': 'Assign Classes'},
        ),
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='dept',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 28, 46, 297556, tzinfo=datetime.timezone.utc)),
        ),
    ]
