# Generated by Django 4.1.2 on 2022-11-04 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_assignclass_options_alter_klass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 45, 28, 495578, tzinfo=datetime.timezone.utc)),
        ),
    ]
