# Generated by Django 4.1.2 on 2022-11-04 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='semester',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 17, 1, 0, 391347, tzinfo=datetime.timezone.utc)),
        ),
    ]
