# Generated by Django 4.1.2 on 2022-11-04 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_semester_klass_year_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klass',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='assignclass',
            old_name='klass_id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Klass_id',
            new_name='class_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 17, 4, 12, 462725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='assignclass',
            unique_together={('subject', 'class_id', 'teacher')},
        ),
    ]
