# Generated by Django 4.1.2 on 2022-11-04 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_klass_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 17, 4, 29, 91773, tzinfo=datetime.timezone.utc)),
        ),
    ]
