# Generated by Django 4.1.2 on 2022-11-10 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_classattendance_assigntime_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 11, 10, 5, 842336, tzinfo=datetime.timezone.utc)),
        ),
    ]
